''' # Generated by Django 3.1.5 on 2021-01-11 10:49
# This migration was created via command using "python manage.py makemigrations"

#It tells django to update the database to include info about the models created

Its a two  step process
1. one is creating the migration, the instructions for how to go about 
manupulating the database . (python manage.py makemigrations)

2. then to take those instructions and actually apply them 
to the underlying database. (python manage.py migrate)

the model that you created is now reflected in this migration

---> how to interact with the table
you can use  direct SQL syntax by opening up the database file and running commands
but Django provides some nice abstraction layers on top of it that you dnt actually 
need to execute those commands urself. you can enter python shell (python manage.py shell)
and just run python commands 
from flights.models import Flight
f = flight(origin="new York", destination="london", duration=415)
f.save()
Flight.objects.all()
'''

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
